
import Head from 'next/head'
const Home : React.FC = ()=>{
  return(
    <div>
    <Head>
        <title>Vendas App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      Teste!!
    </div>
  )

}
export default Home

